version: '3.1'
services: 
  web:
    image: jacobmetzinger/image-gallery
    command: npm start
    ports:
      - "7000:7000"
    depends_on:
      - db
    environment:
      -DATABASE_URL: postgres://postgres@postgres/postgres
    links:
      - db
  proxy-server:
    image: jacobmetzinger/proxy-server
    ports: "80:9000"
  db:
    image: postgres:9.6.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: 'postgres' 
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'postgres'
volumes:
  pgdata: